AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Cluster

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: prod
      CapacityProviders:
      - prod-capacityprovider

  ECSClusterCapProviderAssoc:
    Type: AWS::ECS::ClusterCapacityProviderAssociations
    Properties:
      CapacityProviders: 
        - prod-capacityprovider
      Cluster: prod
      DefaultCapacityProviderStrategy: 
      - CapacityProvider: prod-capacityprovider

Outputs:
  ClusterName:
    Description: Name of the ECS Cluster
    Value: !Ref ECSCluster
