AWSTemplateFormatVersion: '2010-09-09'
Description: Cooltrans Service

Resources:
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: cooltrans
      Cpu: 256
      Memory: 256
      NetworkMode: bridge
      RequiresCompatibilities:
        - EC2
      ExecutionRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/ecs-execution"
      TaskRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-cooltrans"
      ContainerDefinitions:
        - Name: cooltrans
          Image: !Sub "${AWS::AccountId}.dkr.ecr.us-west-2.amazonaws.com/staging/cooltrans:00a242a867a67860f7d3f204dbd1287e2a779215"
          Essential: true
          PortMappings:
            - ContainerPort: 8081
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-group: ecs-prod-cooltrans
              awslogs-region: us-west-2
              awslogs-stream-prefix: ecs-logs

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: cooltrans
      Cluster: prod
      TaskDefinition: !Ref ECSTaskDefinition
      LaunchType: EC2
      DesiredCount: 1
      LoadBalancers:
      - ContainerName: cooltrans
        ContainerPort: 8081
        TargetGroupArn: !Sub "arn:aws:elasticloadbalancing:us-west-2:${AWS::AccountId}:targetgroup/prod-cooltrans/bfb05e95cd9368a2"

Outputs:
  ServiceName:
    Description: Name of the ECS Service
    Value: !Ref ECSService

  TaskDefinition:
    Description: Task Definition
    Value: !Ref ECSTaskDefinition
