AWSTemplateFormatVersion: '2010-09-09'
Description: IAM for a server

Resources:
  EC2Role:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: server
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
      - arn:aws:iam::aws:policy/AmazonSSMManagedEC2InstanceDefaultPolicy
      - !Sub "arn:aws:iam::${AWS::AccountId}:policy/ssh-host-key-sign"

  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName: server
      Path: '/'
      Roles:
        - Ref: EC2Role
