AWSTemplateFormatVersion: '2010-09-09'
Description: IAM for a Tailscale Router

Resources:
  EC2Role:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: tailscale
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonSSMManagedEC2InstanceDefaultPolicy
      - !Sub "arn:aws:iam::${AWS::AccountId}:policy/ssh-host-key-sign"
      Policies:
      - PolicyName: secret-access
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource:
              - !Sub "arn:aws:secretsmanager:us-west-2:${AWS::AccountId}:secret:tailscale-IglZn3"

  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName: tailscale
      Path: '/'
      Roles:
        - Ref: EC2Role
