AWSTemplateFormatVersion: '2010-09-09'
Description: Managed Policy to Allow Assuming Packer Role

Resources:
  PackerRoleAssumePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: packer-user
      Description: "Policy that allows assuming the Packer role"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
            - sts:AssumeRole
            Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/packer"

Outputs:
  PolicyArn:
    Description: "The ARN of the managed policy"
    Value: !Ref PackerRoleAssumePolicy
