AWSTemplateFormatVersion: '2010-09-09'
Description: Managed Policy to Allow signing SSH host keys

Resources:
  SSHHostKeySignPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: ssh-host-key-sign
      Description: "Policy that allows ssh host key signing"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
            - lambda:InvokeFunction
            Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:calambda-ssh-host-key-signing"

Outputs:
  PolicyArn:
    Description: "The ARN of the managed policy"
    Value: !Ref SSHHostKeySignPolicy
