AWSTemplateFormatVersion: '2010-09-09'

Resources:
  LambdaSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: lambda
      GroupDescription: Group tagging traffic from lambdas
      Tags:
      - Key: Name
        Value: lambda
