AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TailscaleSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: tailscale-sg
      GroupDescription: Traffic from tailscale
      Tags:
      - Key: Name
        Value: tailscale-sg
  TailscaleSSHAccess:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: tailscale-ssh-access
      GroupDescription: Allow SSH inbound traffic from tailscale
      Tags:
      - Key: Name
        Value: tailscale-ssh-access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !GetAtt TailscaleSG.GroupId
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: resolve:ssm:/amis/tailscale
        InstanceType: t4g.micro
        IamInstanceProfile:
          Arn: !Sub "arn:aws:iam::${AWS::AccountId}:instance-profile/tailscale"
        EbsOptimized: true
        PrivateDnsNameOptions:
          EnableResourceNameDnsAAAARecord: False
          EnableResourceNameDnsARecord: True
          HostnameType: resource-name
        MetadataOptions:
          HttpTokens: required
        Monitoring:
          Enabled: false
        SecurityGroupIds:
          # - sg-081613d174e1f8e8b # public SSH access if you need to debug something
          - !GetAtt TailscaleSG.GroupId
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            echo "More to come here"
        TagSpecifications:
        - ResourceType: instance
          Tags: 
            - Key: Name
              Value: tailscale
        BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs: 
            DeleteOnTermination: true
            Encrypted: true
            VolumeSize: 8
            VolumeType: gp3

  ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: 
        - us-west-2a
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '1'
