AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ProdSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: prod-sg
      GroupDescription: Traffic from prod
      Tags:
      - Key: Name
        Value: prod-sg
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: resolve:ssm:/amis/server
        InstanceType: t4g.small
        IamInstanceProfile:
          Arn: !Sub "arn:aws:iam::${AWS::AccountId}:instance-profile/server"
        EbsOptimized: true
        PrivateDnsNameOptions:
          EnableResourceNameDnsAAAARecord: False
          EnableResourceNameDnsARecord: True
          HostnameType: resource-name
        MetadataOptions:
          HttpTokens: required
        Monitoring:
          Enabled: false
        SecurityGroupIds:
          # - sg-081613d174e1f8e8b # public SSH access
          - sg-0c421753140d394d3 # Tailscale SSH ingress
          - sg-0624fc02a7ec8da11 # ALB container Ingress
          - !GetAtt ProdSG.GroupId
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            cat <<'EOF' >> /etc/ecs/ecs.config
            ECS_CLUSTER=prod
            ECS_ENABLE_TASK_ENI=true
            ECS_ENABLE_TASK_IAM_ROLE=true
            ECS_LOG_MAX_FILE_SIZE_MB=100
            ECS_LOG_MAX_ROLL_COUNT=3
            ECS_LOG_ROLLOVER_TYPE=size
            ECS_LOGLEVEL=info
            ECS_AVAILABLE_LOGGING_DRIVERS=["awslogs","json-file"]
            EOF

        TagSpecifications:
        - ResourceType: instance
          Tags: 
            - Key: Name
              Value: server
        - ResourceType: volume
          Tags:
            - Key: Name
              Value: server
        BlockDeviceMappings:
        - DeviceName: /dev/xvda 
          Ebs: 
            DeleteOnTermination: true
            Encrypted: true
            VolumeSize: 8
            VolumeType: gp3

  ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: 
        - us-west-2a
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      NewInstancesProtectedFromScaleIn: True
      InstanceMaintenancePolicy:
        MaxHealthyPercentage: 200
        MinHealthyPercentage: 100
      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '1'

  ECSCapacityProvider:
    Type: AWS::ECS::CapacityProvider
    Properties:
      AutoScalingGroupProvider:
        AutoScalingGroupArn: !Ref ASG
        ManagedScaling:
          Status: ENABLED
          TargetCapacity: 100
          MinimumScalingStepSize: 1
          MaximumScalingStepSize: 2
        ManagedTerminationProtection: ENABLED
        ManagedDraining: ENABLED
      Name: prod-capacityprovider
