AWSTemplateFormatVersion: '2010-09-09'
Description: Packer infra

Parameters:
  dockerImage:
    Type: String
    Default: 13a6afa0fd1b1a342d52ba0aed240c961b52b489

Resources:
  ECSPackerServer:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: packer-server
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/ecs-execution"
      TaskRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/packer"
      RuntimePlatform:
        CpuArchitecture : ARM64
        OperatingSystemFamily : LINUX
      ContainerDefinitions:
        - Name: packer
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/staging/packer:${dockerImage}"
          Essential: true
          Command:
          - make
          - server
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-group: ecs-packer-server
              awslogs-region: us-west-2
              awslogs-stream-prefix: ecs-logs

  PackerServerSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: packer for server ami
      FlexibleTimeWindow: 
        MaximumWindowInMinutes: 120
        Mode: FLEXIBLE
      Name: packer-server
      ScheduleExpression: rate(1 days)
      State: ENABLED
      Target: 
        Arn: !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/packer"
        EcsParameters:
          LaunchType: FARGATE
          NetworkConfiguration:
            AwsvpcConfiguration:
              AssignPublicIp: DISABLED
              SecurityGroups: 
              - sg-0cd97e29b526f91ab
              Subnets: 
              - subnet-05c2105bfad11abf9
          PropagateTags: TASK_DEFINITION
          TaskDefinitionArn: !Ref ECSPackerServer
        RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/eventbridge-scheduler"

  ECSPackerTailscale:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: packer-tailscale
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/ecs-execution"
      TaskRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/packer"
      RuntimePlatform:
        CpuArchitecture : ARM64
        OperatingSystemFamily : LINUX
      ContainerDefinitions:
        - Name: packer
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/staging/packer:${dockerImage}"
          Essential: true
          Command:
          - make
          - tailscale
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-group: ecs-packer-tailscale
              awslogs-region: us-west-2
              awslogs-stream-prefix: ecs-logs

  PackerTailscaleSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: packer for tailscale ami
      FlexibleTimeWindow: 
        MaximumWindowInMinutes: 120
        Mode: FLEXIBLE
      Name: packer-tailscale
      ScheduleExpression: rate(1 days)
      State: ENABLED
      Target: 
        Arn: !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/packer"
        EcsParameters:
          LaunchType: FARGATE
          NetworkConfiguration:
            AwsvpcConfiguration:
              AssignPublicIp: ENABLED
              SecurityGroups: 
              - sg-0cd97e29b526f91ab
              Subnets: 
              - subnet-05c2105bfad11abf9
          PropagateTags: TASK_DEFINITION
          TaskDefinitionArn: !Ref ECSPackerTailscale
        RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/eventbridge-scheduler"

